export const SET_SCREEN_TOP = "SET_SCREEN_TOP";
export const SET_SCREEN_READY = "SET_SCREEN_READY";
export const SET_SCREEN_GAME = "SET_SCREEN_GAME";
export const SET_SCREEN_GAME_END = "SET_SCREEN_GAME_END";
export const SET_SCREEN_WINNER = "SET_SCREEN_WINNER";
export const SET_SCREEN_CONTROLS = "SET_SCREEN_CONTROLS";
export const SET_PLAYER_READY = "SET_PLAYER_READY";
export const SET_TIMER = "SET_TIMER";
export const SET_TIMER_INTERVAL_ID = "SET_TIMER_INTERVAL_ID";
export const CANCEL_TIMER_INTERVAL_ID = "CANCEL_TIMER_INTERVAL_ID";
export const END_GAME = "END_GAME";
export const SELECT_ROUND_ANSWER = "SELECT_ROUND_ANSWER";
export const CHANGE_WINNER_NICKNAME = "CHANGE_WINNER_NICKNAME";
export const CHANGE_WINNER_CONTACT = "CHANGE_WINNER_CONTACT";

export const LOAD_LANGUAGE_START = "LOAD_LANGUAGE_START";
export const LOAD_LANGUAGE_SUCCESS = "LOAD_LANGUAGE_SUCCESS";
export const LOAD_LANGUAGE_ERROR = "LOAD_LANGUAGE_ERROR";

export const LOAD_GAME_START = "LOAD_GAME_START";
export const LOAD_GAME_SUCCESS = "LOAD_GAME_SUCCESS";
export const LOAD_GAME_ERROR = "LOAD_GAME_ERROR";

export const LOAD_CONFIG_START = "LOAD_CONFIG_START";
export const LOAD_CONFIG_SUCCESS = "LOAD_CONFIG_SUCCESS";
export const LOAD_CONFIG_ERROR = "LOAD_CONFIG_ERROR";

export const LOAD_TOP_PLAYERS_START = "LOAD_TOP_PLAYERS_START";
export const LOAD_TOP_PLAYERS_SUCCESS = "LOAD_TOP_PLAYERS_SUCCESS";
export const LOAD_TOP_PLAYERS_ERROR = "LOAD_TOP_PLAYERS_ERROR";

export const LOAD_IS_IN_TOP_START = "LOAD_IS_IN_TOP_START";
export const LOAD_IS_IN_TOP_SUCCESS = "LOAD_IS_IN_TOP_SUCCESS";
export const LOAD_IS_IN_TOP_ERROR = "LOAD_IS_IN_TOP_ERROR";

export const END_ROUND_START = "END_ROUND_START";
export const END_ROUND_SUCCESS = "END_ROUND_SUCCESS";
export const END_ROUND_ERROR = "END_ROUND_ERROR";

export const START_ROUND_START = "START_ROUND_START";
export const START_ROUND_SUCCESS = "START_ROUND_SUCCESS";
export const START_ROUND_ERROR = "START_ROUND_ERROR";

export const SAVE_NAME_START = "SAVE_NAME_START";
export const SAVE_NAME_SUCCESS = "SAVE_NAME_SUCCESS";
export const SAVE_NAME_ERROR = "SAVE_NAME_ERROR";

export const LOADER_SHOW = "LOADER_SHOW";
export const LOADER_HIDE = "LOADER_HIDE";
