const SET_SCREEN_TOP = "SET_SCREEN_TOP";
const SET_SCREEN_READY = "SET_SCREEN_READY";
const SET_SCREEN_GAME = "SET_SCREEN_GAME";
const SET_SCREEN_GAME_END = "SET_SCREEN_GAME_END";
const SET_SCREEN_WINNER = "SET_SCREEN_WINNER";
const SET_SCREEN_CONTROLS = "SET_SCREEN_CONTROLS";
const SET_PLAYERS_NUMBER = "SET_PLAYERS_NUMBER";
const SET_PLAYER_READY = "SET_PLAYER_READY";
const SET_TIMER = "SET_TIMER";
const SET_TIMER_INTERVAL_ID = "SET_TIMER_INTERVAL_ID";
const CANCEL_TIMER_INTERVAL_ID = "CANCEL_TIMER_INTERVAL_ID";
const START_GAME_ROUND = "START_GAME_ROUND";
const END_GAME_ROUND = "END_GAME_ROUND";
const END_GAME = "END_GAME";
const SELECT_ROUND_ANSWER = "SELECT_ROUND_ANSWER";
const CALCULATE_ROUND_POINTS = "CALCULATE_ROUND_POINTS";
const SET_WINNER = "SET_WINNER";
const SET_WINNER_LETTER_INDEX = "SET_WINNER_LETTER_INDEX";
const SET_WINNER_LETTER = "SET_WINNER_LETTER";
const SET_WINNER_NICKNAME = "SET_WINNER_NICKNAME";
const SET_GAME_MESSAGE = "SET_GAME_MESSAGE";

const LOAD_CONFIG_START = "LOAD_CONFIG_START";
const LOAD_CONFIG_SUCCESS = "LOAD_CONFIG_SUCCESS";
const LOAD_CONFIG_ERROR = "LOAD_CONFIG_ERROR";

const LOAD_GAME_START = "LOAD_GAME_START";
const LOAD_GAME_SUCCESS = "LOAD_GAME_SUCCESS";
const LOAD_GAME_ERROR = "LOAD_GAME_ERROR";

export {
  SET_SCREEN_TOP,
  SET_SCREEN_READY,
  SET_SCREEN_GAME,
  SET_SCREEN_WINNER,
  SET_SCREEN_GAME_END,
  SET_PLAYERS_NUMBER,
  SET_PLAYER_READY,
  SET_SCREEN_CONTROLS,
  SET_TIMER,
  SET_TIMER_INTERVAL_ID,
  CANCEL_TIMER_INTERVAL_ID,
  START_GAME_ROUND,
  END_GAME_ROUND,
  SELECT_ROUND_ANSWER,
  CALCULATE_ROUND_POINTS,
  SET_WINNER,
  SET_WINNER_LETTER_INDEX,
  SET_WINNER_LETTER,
  SET_WINNER_NICKNAME,
  SET_GAME_MESSAGE,
  LOAD_GAME_START,
  LOAD_GAME_SUCCESS,
  LOAD_GAME_ERROR,
  LOAD_CONFIG_START,
  LOAD_CONFIG_SUCCESS,
  LOAD_CONFIG_ERROR,
  END_GAME
};
