const SET_SCREEN_TOP = "SET_SCREEN_TOP";
const SET_SCREEN_READY = "SET_SCREEN_READY";
const SET_SCREEN_GAME = "SET_SCREEN_GAME";
const SET_SCREEN_GAME_END = "SET_SCREEN_GAME_END";
const SET_SCREEN_WINNER = "SET_SCREEN_WINNER";
const SET_SCREEN_CONTROLS = "SET_SCREEN_CONTROLS";
const SET_PLAYER_READY = "SET_PLAYER_READY";
const SET_TIMER = "SET_TIMER";
const SET_TIMER_INTERVAL_ID = "SET_TIMER_INTERVAL_ID";
const CANCEL_TIMER_INTERVAL_ID = "CANCEL_TIMER_INTERVAL_ID";
const START_GAME_ROUND = "START_GAME_ROUND";
const END_GAME_ROUND = "END_GAME_ROUND";
const END_GAME = "END_GAME";
const SELECT_ROUND_ANSWER = "SELECT_ROUND_ANSWER";
const CHANGE_WINNER_NICKNAME = "CHANGE_WINNER_NICKNAME";
const CHANGE_WINNER_CONTACT = "CHANGE_WINNER_CONTACT";
const SET_GAME_MESSAGE = "SET_GAME_MESSAGE";

const LOAD_GAME_START = "LOAD_GAME_START";
const LOAD_GAME_SUCCESS = "LOAD_GAME_SUCCESS";
const LOAD_GAME_ERROR = "LOAD_GAME_ERROR";

const LOAD_CONFIG_START = "LOAD_CONFIG_START";
const LOAD_CONFIG_SUCCESS = "LOAD_CONFIG_SUCCESS";
const LOAD_CONFIG_ERROR = "LOAD_CONFIG_ERROR";

const LOAD_TOP_PLAYERS_START = "LOAD_TOP_PLAYERS_START";
const LOAD_TOP_PLAYERS_SUCCESS = "LOAD_TOP_PLAYERS_SUCCESS";
const LOAD_TOP_PLAYERS_ERROR = "LOAD_TOP_PLAYERS_ERROR";

const LOAD_IS_IN_TOP_START = "LOAD_IS_IN_TOP_START";
const LOAD_IS_IN_TOP_SUCCESS = "LOAD_IS_IN_TOP_SUCCESS";
const LOAD_IS_IN_TOP_ERROR = "LOAD_IS_IN_TOP_ERROR";

const LOADER_SHOW = "LOADER_SHOW";
const LOADER_HIDE = "LOADER_HIDE";

export {
  SET_SCREEN_TOP,
  SET_SCREEN_READY,
  SET_SCREEN_GAME,
  SET_SCREEN_WINNER,
  SET_SCREEN_GAME_END,
  SET_PLAYER_READY,
  SET_SCREEN_CONTROLS,
  SET_TIMER,
  SET_TIMER_INTERVAL_ID,
  CANCEL_TIMER_INTERVAL_ID,
  START_GAME_ROUND,
  END_GAME_ROUND,
  SELECT_ROUND_ANSWER,
  CHANGE_WINNER_NICKNAME,
  CHANGE_WINNER_CONTACT,
  SET_GAME_MESSAGE,
  LOAD_GAME_START,
  LOAD_GAME_SUCCESS,
  LOAD_GAME_ERROR,
  LOAD_CONFIG_START,
  LOAD_CONFIG_SUCCESS,
  LOAD_CONFIG_ERROR,
  END_GAME,
  LOAD_TOP_PLAYERS_START,
  LOAD_TOP_PLAYERS_SUCCESS,
  LOAD_TOP_PLAYERS_ERROR,
  LOAD_IS_IN_TOP_START,
  LOAD_IS_IN_TOP_SUCCESS,
  LOAD_IS_IN_TOP_ERROR,
  LOADER_SHOW,
  LOADER_HIDE
};
