export const LOAD_TOP_PLAYERS_START = "LOAD_TOP_PLAYERS_START";
export const LOAD_TOP_PLAYERS_SUCCESS = "LOAD_TOP_PLAYERS_SUCCESS";
export const LOAD_TOP_PLAYERS_ERROR = "LOAD_TOP_PLAYERS_ERROR";

export const LOAD_GAMES_START = "LOAD_GAMES_START";
export const LOAD_GAMES_SUCCESS = "LOAD_GAMES_SUCCESS";
export const LOAD_GAMES_ERROR = "LOAD_GAMES_ERROR";

export const LOAD_CONFIG_START = "LOAD_CONFIG_START";
export const LOAD_CONFIG_SUCCESS = "LOAD_CONFIG_SUCCESS";
export const LOAD_CONFIG_ERROR = "LOAD_CONFIG_ERROR";

export const SAVE_CONFIG_START = "SAVE_CONFIG_START";
export const SAVE_CONFIG_SUCCESS = "SAVE_CONFIG_SUCCESS";
export const SAVE_CONFIG_ERROR = "SAVE_CONFIG_ERROR";

export const CONFIG_PROPERTY_CHANGE = "CONFIG_PROPERTY_CHANGE";

export const IMAGE_PROPERTY_CHANGE = "IMAGE_PROPERTY_CHANGE";
export const ADD_INCORRECT_ANSWER = "ADD_INCORRECT_ANSWER";
export const REMOVE_INCORRECT_ANSWER = "REMOVE_INCORRECT_ANSWER";
export const CHANGE_INCORRECT_ANSWER = "CHANGE_INCORRECT_ANSWER";

export const SAVE_IMAGE_START = "SAVE_IMAGE_START";
export const SAVE_IMAGE_SUCCESS = "SAVE_IMAGE_SUCCESS";
export const SAVE_IMAGE_ERROR = "SAVE_IMAGE_ERROR";
