export const LOAD_TOP_PLAYERS_START = "LOAD_TOP_PLAYERS_START";
export const LOAD_TOP_PLAYERS_SUCCESS = "LOAD_TOP_PLAYERS_SUCCESS";
export const LOAD_TOP_PLAYERS_ERROR = "LOAD_TOP_PLAYERS_ERROR";

export const LOAD_GAMES_START = "LOAD_GAMES_START";
export const LOAD_GAMES_SUCCESS = "LOAD_GAMES_SUCCESS";
export const LOAD_GAMES_ERROR = "LOAD_GAMES_ERROR";

export const LOAD_GAME_START = "LOAD_GAME_START";
export const LOAD_GAME_SUCCESS = "LOAD_GAME_SUCCESS";
export const LOAD_GAME_ERROR = "LOAD_GAME_ERROR";

export const LOAD_CONFIG_START = "LOAD_CONFIG_START";
export const LOAD_CONFIG_SUCCESS = "LOAD_CONFIG_SUCCESS";
export const LOAD_CONFIG_ERROR = "LOAD_CONFIG_ERROR";

export const SAVE_CONFIG_START = "SAVE_CONFIG_START";
export const SAVE_CONFIG_SUCCESS = "SAVE_CONFIG_SUCCESS";
export const SAVE_CONFIG_ERROR = "SAVE_CONFIG_ERROR";

export const CONFIG_PROPERTY_CHANGE = "CONFIG_PROPERTY_CHANGE";

export const IMAGE_DATA_CLEAR = "IMAGE_DATA_CLEAR";
export const IMAGE_PROPERTY_CHANGE = "IMAGE_PROPERTY_CHANGE";
export const ADD_INCORRECT_ANSWER = "ADD_INCORRECT_ANSWER";
export const REMOVE_INCORRECT_ANSWER = "REMOVE_INCORRECT_ANSWER";
export const CHANGE_INCORRECT_ANSWER = "CHANGE_INCORRECT_ANSWER";

export const SAVE_IMAGE_START = "SAVE_IMAGE_START";
export const SAVE_IMAGE_SUCCESS = "SAVE_IMAGE_SUCCESS";
export const SAVE_IMAGE_ERROR = "SAVE_IMAGE_ERROR";

export const LOAD_IMAGE_START = "LOAD_IMAGE_START";
export const LOAD_IMAGE_SUCCESS = "LOAD_IMAGE_SUCCESS";
export const LOAD_IMAGE_ERROR = "LOAD_IMAGE_ERROR";

export const LOAD_IMAGES_START = "LOAD_IMAGES_START";
export const LOAD_IMAGES_SUCCESS = "LOAD_IMAGES_SUCCESS";
export const LOAD_IMAGES_ERROR = "LOAD_IMAGES_ERROR";

export const REMOVE_IMAGE_START = "REMOVE_IMAGE_START";
export const REMOVE_IMAGE_SUCCESS = "REMOVE_IMAGE_SUCCESS";
export const REMOVE_IMAGE_ERROR = "REMOVE_IMAGE_ERROR";

export const LOADER_SHOW = "LOADER_SHOW";
export const LOADER_HIDE = "LOADER_HIDE";

export const ERROR_SHOW = "ERROR_SHOW";
export const ERROR_HIDE = "ERROR_HIDE";

export const SUCCESS_SHOW = "SUCCESS_SHOW";
export const SUCCESS_HIDE = "SUCCESS_HIDE";

export const REMOVE_GAMES_START = "REMOVE_GAMES_START";
export const REMOVE_GAMES_SUCCESS = "REMOVE_GAMES_SUCCESS";
export const REMOVE_GAMES_ERROR = "REMOVE_GAMES_ERROR";

export const REMOVE_GAME_START = "REMOVE_GAME_START";
export const REMOVE_GAME_SUCCESS = "REMOVE_GAME_SUCCESS";
export const REMOVE_GAME_ERROR = "REMOVE_GAME_ERROR";
