export const SET_SCREEN_DASHBOARD = "SET_SCREEN_DASHBOARD";
export const SET_SCREEN_TOP_PLAYERS = "SET_SCREEN_TOP_PLAYERS";

export const LOAD_TOP_PLAYERS_START = "LOAD_TOP_PLAYERS_START";
export const LOAD_TOP_PLAYERS_SUCCESS = "LOAD_TOP_PLAYERS_SUCCESS";
export const LOAD_TOP_PLAYERS_ERROR = "LOAD_TOP_PLAYERS_ERROR";
