const SET_SCREEN_TOP = "SET_SCREEN_TOP";
const SET_SCREEN_READY = "SET_SCREEN_READY";
const SET_SCREEN_GAME = "SET_SCREEN_GAME";
const SET_SCREEN_CONTROLS = "SET_SCREEN_CONTROLS";
const SET_PLAYERS_NUMBER = "SET_PLAYERS_NUMBER";
const SET_PLAYER_READY = "SET_PLAYER_READY";
const SET_TIMER = "SET_TIMER";
const SET_TIMER_INTERVAL_ID = "SET_TIMER_INTERVAL_ID";
const CANCEL_TIMER_INTERVAL_ID = "CANCEL_TIMER_INTERVAL_ID";

module.exports = {
  SET_SCREEN_TOP,
  SET_SCREEN_READY,
  SET_SCREEN_GAME,
  SET_PLAYERS_NUMBER,
  SET_PLAYER_READY,
  SET_SCREEN_CONTROLS,
  SET_TIMER,
  SET_TIMER_INTERVAL_ID,
  CANCEL_TIMER_INTERVAL_ID
};
