const SET_SCREEN_TOP = "SET_SCREEN_TOP";
const SET_SCREEN_READY = "SET_SCREEN_READY";
const SET_PLAYERS_NUMBER = "SET_PLAYERS_NUMBER";
const SET_PLAYER_READY = "SET_PLAYER_READY";

module.exports = {
  SET_SCREEN_TOP,
  SET_SCREEN_READY,
  SET_PLAYERS_NUMBER,
  SET_PLAYER_READY
};
