const CONTROLS_SCREEN_TIMER = 1;
const GAME_SCREEN_TIMER = 10;
const INITIAL_PLAYERS = 1;
const MIN_PLAYERS = 1;
const MAX_PLAYERS = 2;
const ROUNDS_IN_GAME = 5;
const ANSWERS_IN_ROUND = 4;
const POINTS_PER_ROUND = 10;
const WINNER_NICKNAME_MAX_LETTERS = 10;
const NICKNAME_LETTER_TABLE = "0123456789_ABCDEFGHIJKLMNOPQRSTUVWXYZ";
const TOP_PLAYERS = 5;

module.exports = {
  INITIAL_PLAYERS,
  MIN_PLAYERS,
  MAX_PLAYERS,
  CONTROLS_SCREEN_TIMER,
  GAME_SCREEN_TIMER,
  ROUNDS_IN_GAME,
  ANSWERS_IN_ROUND,
  POINTS_PER_ROUND,
  WINNER_NICKNAME_MAX_LETTERS,
  NICKNAME_LETTER_TABLE,
  TOP_PLAYERS
};
