const CONTROLS_SCREEN_TIMER = 3;
const GAME_SCREEN_TIMER = 10;
const INITIAL_PLAYERS = 1;
const MIN_PLAYERS = 1;
const MAX_PLAYERS = 2;
const ROUNDS_IN_GAME = 3;
const ANSWERS_IN_ROUND = 4;

module.exports = {
  INITIAL_PLAYERS,
  MIN_PLAYERS,
  MAX_PLAYERS,
  CONTROLS_SCREEN_TIMER,
  GAME_SCREEN_TIMER,
  ROUNDS_IN_GAME,
  ANSWERS_IN_ROUND
};
