const CONTROLS_SCREEN_TIMER = 10;
const GAME_SCREEN_TIMER = 15;
const INITIAL_PLAYERS = 1;
const MIN_PLAYERS = 1;
const MAX_PLAYERS = 4;

module.exports = {
  INITIAL_PLAYERS,
  MIN_PLAYERS,
  MAX_PLAYERS,
  CONTROLS_SCREEN_TIMER,
  GAME_SCREEN_TIMER
};
